development:
  secret_key_base: <%= ENV["APP_SESSION_SECRET"] || "test" %>

test:
  secret_key_base: <%= ENV["APP_SESSION_SECRET"] || "test" %>

production:
  secret_key_base: <%= ENV["APP_SESSION_SECRET"] %>
